app:
  version: 1.0.0
  name: cherkizon

email:
  from: finstart.mailer@molbulak.com
  username: finstart.mailer
  password: Shaxz0da201306
  host: mail.molbulak.com
  address: mail.molbulak.com
  port: 25
  encoding: utf-8

healthcheck:
  token: f567a8da21a261ed67f46ba07defecd9
  url: http://localhost:9090/graph

alerts:
  emails:
    - a.itskovich@molbulak.com

fr:
  url: http://10.1.2.103:8091
  developer_id: 106567582

sh:
  executor: C:\Program Files\Git\bin\bash.exe

server:
  port: 8081

loggers:
  sql:
    backup_count: 3
  http:
    backup_count: 3

agent:
  port: 4001

unikron:
  host: http://localhost:8082

prod:
  db:
    host: localhost
    port: 5432
    user: postgres
    password: 92559255


dev:
  pgdb:
    host: localhost
    port: 3
    user: postgres
    password: 92559255
  db:
    disable_pool: True
    db_monitoring_enabled: False
    host: 192.168.200.250
    database: D:\Finance\IB_Base\DB_1_LAST.IB
    port: 3050
    url: 192.168.200.250/3050:D:\Finance\IB_Base\DB_1_LAST.IB
    username: SYSDBA
    password: F!ora80X

