from event_bus import EventBus

EVENT_DEPLOY_HEALTHCHECK_FAILED = "EVENT_DEPLOY_HEALTHCHECK_FAILED"
EVENT_DEPLOY_HEALTHCHECK_FIXED = "EVENT_DEPLOY_HEALTHCHECK_FIXED"
EVENT_DEPLOY_RESTARTED = "EVENT_DEPLOY_RESTARTED"
EVENT_DEPLOY_STOPPED = "EVENT_DEPLOY_STOPPED"

event_bus = EventBus()
