from event_bus import EventBus

EVENT_SERVICE_REMOVED = "EVENT_SERVICE_REMOVED"
EVENT_SERVICE_REGISTERED = "EVENT_SERVICE_REGISTERED"
EVENT_DEPLOY_REGISTERED = "EVENT_DEPLOY_REGISTERED"

event_bus = EventBus()
