from event_bus import EventBus

EVENT_HEALTHCHECK_RESULT_RECEIVED = "EVENT_HEALTHCHECK_RESULT_RECEIVED"
EVENT_DEPLOY_RESTARTED = "EVENT_DEPLOY_RESTARTED"
EVENT_DEPLOY_STOPPED = "EVENT_DEPLOY_STOPPED"

event_bus = EventBus()
